USE [master]
GO
/****** Object:  Database [Gestao]    Script Date: 08/02/2023 21:41:05 ******/
CREATE DATABASE [Gestao]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Gestao', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\Gestao.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Gestao_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\Gestao_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Gestao] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Gestao].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Gestao] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Gestao] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Gestao] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Gestao] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Gestao] SET ARITHABORT OFF 
GO
ALTER DATABASE [Gestao] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Gestao] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Gestao] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Gestao] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Gestao] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Gestao] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Gestao] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Gestao] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Gestao] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Gestao] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Gestao] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Gestao] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Gestao] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Gestao] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Gestao] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Gestao] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Gestao] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Gestao] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Gestao] SET  MULTI_USER 
GO
ALTER DATABASE [Gestao] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Gestao] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Gestao] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Gestao] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Gestao] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Gestao] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Gestao] SET QUERY_STORE = OFF
GO
USE [Gestao]
GO
/****** Object:  Table [dbo].[GrupoUsuario]    Script Date: 08/02/2023 21:41:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GrupoUsuario](
	[ID] [int] NOT NULL,
	[GrupoUsuario] [varchar](50) NULL,
 CONSTRAINT [PK_GrupoUsuario] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Permissao]    Script Date: 08/02/2023 21:41:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Permissao](
	[ID] [int] NOT NULL,
	[Descricao] [varchar](50) NULL,
 CONSTRAINT [PK_Permissao] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PermissaoGrupoUsuario]    Script Date: 08/02/2023 21:41:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PermissaoGrupoUsuario](
	[ID_Permissao] [int] NOT NULL,
	[ID_GrupoUsuario] [int] NOT NULL,
 CONSTRAINT [PK_PermissaoGrupoUsuario] PRIMARY KEY CLUSTERED 
(
	[ID_Permissao] ASC,
	[ID_GrupoUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 08/02/2023 21:41:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](150) NOT NULL,
	[NOME_USUARIO] [varchar](50) NOT NULL,
	[CPF_USUARIO] [varchar](18) NOT NULL,
	[EMAIL_USUARIO] [varchar](150) NULL,
	[SENHA_USUARIO] [varchar](50) NULL,
	[ATIVO] [bit] NOT NULL,
	[DATA_CADASTRO] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UsuarioGrupoUsuario]    Script Date: 08/02/2023 21:41:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UsuarioGrupoUsuario](
	[ID_Usuario] [int] NOT NULL,
	[ID_GrupoUsuario] [int] NOT NULL,
 CONSTRAINT [PK_UsuarioGrupoUsuario] PRIMARY KEY CLUSTERED 
(
	[ID_Usuario] ASC,
	[ID_GrupoUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USUARIO] ADD  DEFAULT (CONVERT([date],getdate())) FOR [DATA_CADASTRO]
GO
ALTER TABLE [dbo].[PermissaoGrupoUsuario]  WITH CHECK ADD  CONSTRAINT [FK_PermissaoGrupoUsuario_GrupoUsuario] FOREIGN KEY([ID_GrupoUsuario])
REFERENCES [dbo].[GrupoUsuario] ([ID])
GO
ALTER TABLE [dbo].[PermissaoGrupoUsuario] CHECK CONSTRAINT [FK_PermissaoGrupoUsuario_GrupoUsuario]
GO
ALTER TABLE [dbo].[PermissaoGrupoUsuario]  WITH CHECK ADD  CONSTRAINT [FK_PermissaoGrupoUsuario_Permissao] FOREIGN KEY([ID_Permissao])
REFERENCES [dbo].[Permissao] ([ID])
GO
ALTER TABLE [dbo].[PermissaoGrupoUsuario] CHECK CONSTRAINT [FK_PermissaoGrupoUsuario_Permissao]
GO
ALTER TABLE [dbo].[UsuarioGrupoUsuario]  WITH CHECK ADD  CONSTRAINT [FK_UsuarioGrupoUsuario_GrupoUsuario] FOREIGN KEY([ID_GrupoUsuario])
REFERENCES [dbo].[GrupoUsuario] ([ID])
GO
ALTER TABLE [dbo].[UsuarioGrupoUsuario] CHECK CONSTRAINT [FK_UsuarioGrupoUsuario_GrupoUsuario]
GO
ALTER TABLE [dbo].[UsuarioGrupoUsuario]  WITH CHECK ADD  CONSTRAINT [FK_UsuarioGrupoUsuario_USUARIO] FOREIGN KEY([ID_Usuario])
REFERENCES [dbo].[USUARIO] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[UsuarioGrupoUsuario] CHECK CONSTRAINT [FK_UsuarioGrupoUsuario_USUARIO]
GO
USE [master]
GO
ALTER DATABASE [Gestao] SET  READ_WRITE 
GO
